### ISSUE TITLE
Entity functions don't work since CScriptVars in TinyJS can't hold 64-bit integers for UniqueIDs

### ISSUE THREAD

**Issue by byteandahalf** [ryanterry131/modpe_ios#2]
I'll fix this in TinyJS and submit a pull request to the official repo.

**Comment by jose-vm** [comment]
Store the entity ids in a string and the parse it, duh

**Comment by byteandahalf** [comment]
That works only one way. I still need to be able to send uint64_ts to JS.

**Comment by byteandahalf** [comment]
I have developed a system to workaround this, but I haven't pushed it yet.

**Comment by TheDiamondYT1** [comment]
Is this dead?

**Comment by TheDiamondYT1** [comment]
Im thinking of making C# ModPE api

**Comment by ryanterry131** [comment]
Turns out the crash was caused by something else that I've solved, and UUIDs are passed as strings now. Closed.
